type Query {
    recipe(_id: String!): Recipe
    recipes(page: Int!, mine: Boolean): RecipeList
}

type Mutation {
    createRecipe(recipe: RecipeInput!): String
    replaceRecipe(recipe: RecipeInput!): String
    removeRecipe(_id: String!): [Boolean]
}

type Recipe {
    _id: String
    title: String
    url: String
    user: String
    ingredients: [Ingredient]
}

type Ingredient {
    title: String
    amount: Float
    unit: String
}

input RecipeInput {
    _id: String
    title: String!
    url: String
    ingredients: [IngredientInput]!
}

input IngredientInput {
    title: String
    amount: Float
    unit: String
}

type RecipeList {
    items: [Recipe]
    numPages: Int
}
