extends:
  - airbnb
  - plugin:@wordpress/eslint-plugin/esnext
  - plugin:@typescript-eslint/recommended
env:
  browser: false
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
globals:
  wp: true
  window: true
  document: true
plugins:
  - react
  - jsx-a11y
  - import
  - "@typescript-eslint"
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    webpack:
      config: webpack.config.babel.js
rules:
  template-curly-spacing: ["error", "never"]
  no-console: off
  react/react-in-jsx-scope: off
  operator-linebreak: ["error", "after"]
  max-len: ["error", 150, 2]
  click-events-have-key-events: off
  react/prop-types: off
  react/prefer-stateless-function: off
  import/no-extraneous-dependencies: off
  class-methods-use-this: off
  react/destructuring-assignment: off
  react/no-danger: off
  indent:
    - error
    - 2
    - SwitchCase: 1
  space-in-parens: ["error", "never"]
  computed-property-spacing: ["error", "never"]
  space-unary-ops:
    - error
    - words: true
  nonwords: 0
  array-bracket-spacing: ["error", "never"]
  react/jsx-filename-extension:
    - 2
    - extensions:
      - ".jsx"
      - ".tsx"
  react/no-string-refs: off
  lines-between-class-members: off
  import/no-cycle: off
  "@typescript-eslint/no-inferrable-types": off
overrides:
  - files:
    - "*.js"
    - "*.jsx"
    rules:
      "@typescript-eslint/explicit-function-return-type": off
  - files:
    - "*.ts"
    - "*.tsx"
    rules:
      jsx-a11y/control-has-associated-label: off
      "@typescript-eslint/ban-ts-ignore": off
