services:
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017

    mysql:
        container_name: mysql
        image: mariadb:10.5
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306

    wordpress:
        container_name: wordpress
        image: wordpress:latest
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_NAME: ${MYSQL_DB}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DEBUG: 0
            TZ: America/Toronto
            MONGO: mongo
            NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
            NODE_ENV: development
            VERSION: ${NEXT_PUBLIC_VERSION}
        volumes:
            - ./wordpress/plugins/2d-tag-cloud:/var/www/html/wp-content/plugins/2d-tag-cloud
            - ./wordpress/themes/sujin:/var/www/html/wp-content/themes/sujin
            - ./wordpress/uploads:/var/www/html/wp-content/uploads
        ports:
            - 9000:80
    # sujin:
    #     container_name: sujin
    #     image: nextjs-docker
    #     depends_on:
    #         - mysql
    #         - mongo
    #     environment:
    #         MYSQL: mysql
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #         MYSQL_DB: ${MYSQL_DB}
    #         MONGO: mongo
    #         PORT: 80
    #         TITLE: ${TITLE}
    #         EXCERPT: ${EXCERPT}
    #         FRONTEND: ${FRONTEND}
    #         WORDPRESS: ${WORDPRESS}
    #         FLICKR_ID: ${FLICKR_ID}
    #         NEXT_PUBLIC_GOOGLE_AD_CLIENT: ${NEXT_PUBLIC_GOOGLE_AD_CLIENT}
    #         NEXT_PUBLIC_GOOGLE_AD_CLIENT: ${NEXT_PUBLIC_GOOGLE_AD_CLIENT}
    #         SERVER_SECRET: ${SERVER_SECRET}
    #         VERSION: ${VERSION}
    #     ports:
    #         - 80:80
