services:
    sujin_mongo:
        container_name: sujin_mongo
        image: mongo:8.2
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - mongo:/data/db
        networks:
            - sujin_database

    sujin_redis:
        container_name: sujin_redis
        image: redis:8.4.0-alpine
        restart: always
        ports:
            - 6379:6379
        networks:
            - sujin_redis

    sujin_next:
        container_name: sujin_next
        image: sujin2f/next:12.0.1
        restart: always
        environment:
            SITE_NAME: ${SITE_NAME}
            SITE_DESCRIPTION: ${SITE_DESCRIPTION}
            NEXT_BASE_URL: ${NEXT_BASE_URL}
            GQL_BASE_URL: http://sujin_graphql
            AUTH_BASE_URL: ${AUTH_BASE_URL}
            GOOGLE_AD_CLIENT: ${GOOGLE_AD_CLIENT}
            GOOGLE_AD_SLOT_FOOTER: ${GOOGLE_AD_SLOT_FOOTER}
            GOOGLE_AD_SLOT_SIDEBAR: ${GOOGLE_AD_SLOT_SIDEBAR}
            INTER_COM_SECRET: ${INTER_COM_SECRET}
            CRYPTO_KEY: ${CRYPTO_KEY}
            REDIS_ENDPOINT:
            BYPASS_CACHE: ${BYPASS_CACHE}
        ports:
            - ${NEXT_SERVER_PORT}:80
        volumes:
            - ./@next/public:/app/public
        networks:
            - sujin_public
            - sujin_graphql
            - sujin_redis

volumes:
    mongo:

# Networks:
#   - In dev environment, put everything into sujin_public
# sujin_public    Public network to web
#                 @auth, @next, @wordpress
#                 docker network create sujin_public.
#
# sujin_database  Private network for databases
#                 @graphql, mysql, mongo
#                 docker network create --internal sujin_database.
#
# sujin_wordpress Private network for WP
#                 @wordpress, mysql
#                 docker network create --internal sujin_wordpress.
#
# sujin_redis     Private network for Redis
#                 @wordpress, @next, @graphql, redis
#                 docker network create --internal sujin_redis.
#
# sujin_graphql   Private network for Graphql
#                 @next, @auth, @wordpress, @graphql
#                 docker network create --internal sujin_graphql.
networks:
    sujin_public:
        external: true
        internal: false
    sujin_database:
        external: true
        internal: true
    sujin_wordpress:
        external: true
        internal: true
    sujin_redis:
        external: true
        internal: true
    sujin_graphql:
        external: true
        internal: true
