services:
    nginx-proxy:
        container_name: nginx-proxy
        build:
            dockerfile: Dockerfile-nginx-proxy
        restart: always
        volumes:
            - certs:/etc/nginx/certs
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - conf.d:/etc/nginx/conf.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
            - 443:443
        networks:
            - sujin_public

    nginx-proxy-acme:
        container_name: nginx-proxy-acme
        image: nginxproxy/acme-companion
        restart: always
        volumes_from:
            - nginx-proxy
        volumes:
            - acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            DEFAULT_EMAIL: sujin.2f@gmail.com
        networks:
            - sujin_public

    sujin_mongo:
        container_name: sujin_mongo
        image: mongo:8.2
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - sujin_mongo:/data/db
        networks:
            - sujin_database

    sujin_mysql:
        container_name: sujin_mysql
        image: mariadb:12.1.2-ubi10
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - sujin_mysql:/var/lib/mysql
        networks:
            - sujin_database
            - sujin_wordpress

    sujin_redis:
        container_name: sujin_redis
        image: redis:8.4.0-alpine
        restart: always
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis-sysctl.conf:/etc/sysctl.conf
        ports:
            - 6379:6379
        networks:
            - sujin_redis

    sujin_wordpress:
        container_name: sujin_wordpress
        image: sujin2f/wordpress:12.0.0-beta.3
        restart: always
        environment:
            WORDPRESS_DB_HOST: sujin_mysql
            WORDPRESS_DB_NAME: ${MYSQL_DB}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DEBUG: 0
            TZ: America/Toronto
            INTER_COM_SECRET: ${INTER_COM_SECRET}
            CRYPTO_KEY: ${CRYPTO_KEY}
            GQL_ENDPOINT: https://graphql.sujinc.com
            NEXT_ENDPOINT: https://sujinc.com
            VIRTUAL_HOST: cms.sujinc.com
            LETSENCRYPT_HOST: cms.sujinc.com
        volumes:
            - ./public/wp-content/uploads:/var/www/html/wp-content/uploads
        networks:
            - sujin_public
            - sujin_wordpress
            - sujin_graphql

    sujin_graphql:
        container_name: sujin_graphql
        image: sujin2f/graphql:12.0.1
        restart: always
        environment:
            SERVER_PORT: 80
            ACCESS_SECRET: ${ACCESS_SECRET}
            REFRESH_SECRET: ${REFRESH_SECRET}
            INTER_COM_SECRET: ${INTER_COM_SECRET}
            EMAIL_SECRET: ${EMAIL_SECRET}
            CRYPTO_KEY: ${CRYPTO_KEY}
            CORS_ORIGINS: '["https://sujinc.com","https://cms.sujinc.com","https://auth.sujinc.com"]'
            MONGO: sujin_mongo:27017
            MYSQL: sujin_mysql
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DB: ${MYSQL_DB}
            MONGO_DATABASE: ${MONGO_DATABASE}
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            FLICKR_ID: ${FLICKR_ID}
        ports:
            - 80:80
        networks:
            - sujin_database
            - sujin_graphql

    sujin_auth:
        container_name: sujin_auth
        image: sujin2f/auth:12.0.0-beta.2
        restart: always
        environment:
            SERVER_PORT: 80
            BASE_URL: https://auth.sujinc.com
            GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}0
            GOOGLE_REDIRECT_URI: https://auth.sujinc.com/google/auth/callback
            GQL_ENDPOINT: https://graphql.sujinc.com
            CORS_ORIGINS: '["https://sujinc.com", "https://auth.sujinc.com"]'
            SESSION_SECRET: ${SESSION_SECRET}
            INTER_COM_SECRET: ${INTER_COM_SECRET}
            CRYPTO_KEY: ${CRYPTO_KEY}
            VIRTUAL_HOST: auth.sujinc.com
            LETSENCRYPT_HOST: auth.sujinc.com
        networks:
            - sujin_public
            - sujin_graphql

    sujin_next:
        container_name: sujin_next
        image: sujin2f/next:12.0.1
        restart: always
        environment:
            SITE_NAME: ${SITE_NAME}
            SITE_DESCRIPTION: ${SITE_DESCRIPTION}
            BASE_URL: ${BASE_URL}
            GOOGLE_AD_CLIENT: ${GOOGLE_AD_CLIENT}
            GOOGLE_AD_SLOT_FOOTER: ${GOOGLE_AD_SLOT_FOOTER}
            GOOGLE_AD_SLOT_SIDEBAR: ${GOOGLE_AD_SLOT_SIDEBAR}
            AUTH_ENDPOINT: https://auth.sujinc.com
            GQL_ENDPOINT: http://sujin_graphql
            INTER_COM_SECRET: ${INTER_COM_SECRET}
            CRYPTO_KEY: ${CRYPTO_KEY}
            REDIS_SERVER: ":${REDIS_PASSWORD}@sujin_redis:6379"
            VIRTUAL_HOST: sujinc.com
            LETSENCRYPT_HOST: sujinc.com
        volumes:
            - ./public:/app/public
        networks:
            - sujin_public
            - sujin_graphql
            - sujin_redis
volumes:
    certs:
    vhost:
    html:
    conf.d:
    acme:
    sujin_mongo:
        external: true
    sujin_mysql:
        external: true

# Networks:
#   - In dev environment, put everything into sujin_public
# sujin_public    Public network to web
#                 @auth, @next, @wordpress
#                 docker network create sujin_public.
#
# sujin_database  Private network for databases
#                 @graphql, mysql, mongo
#                 docker network create --internal sujin_database.
#
# sujin_wordpress Private network for WP
#                 @wordpress, mysql
#                 docker network create --internal sujin_wordpress.
#
# sujin_redis     Private network for Redis
#                 @next, redis
#                 docker network create --internal sujin_redis.
#
# sujin_graphql   Private network for Graphql
#                 @next, @auth, @wordpress, @graphql
#                 docker network create --internal sujin_graphql.
networks:
    sujin_public:
        external: true
        internal: false
    sujin_database:
        external: true
        internal: true
    sujin_wordpress:
        external: true
        internal: true
    sujin_redis:
        external: true
        internal: true
    sujin_graphql:
        external: true
        internal: true
