version: "2"
services:
  sujinc:
    container_name: sujinc
    image: "wordpress"
    environment:
        - VIRTUAL_HOST=sujinc.com
        - WORDPRESS_DB_NAME=sujinc.com
        - WORDPRESS_DB_USER=root
        - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
        - WORDPRESS_DEBUG=0
        - TZ=America/Toronto
    volumes:
      - /Users/sujin/Development/Docker/wp-content/sujinc.com:/var/www/html/wp-content
      - ./:/var/www/html/wp-content/themes/sujin
    expose:
      - 80
    links:
      - mysql
    network_mode: bridge
  mysql:
    container_name: mysql
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    network_mode: bridge
volumes:
  mysql:
