# syntax=docker.io/docker/dockerfile:1

FROM node:24

WORKDIR /
RUN mkdir /@lib
RUN mkdir /@common
RUN mkdir /@common/node-cache
RUN mkdir /@common/share
COPY @lib/dist /@lib/dist
COPY @common/node-cache/dist /@common/node-cache/dist
COPY @common/share/dist /@common/share/dist

WORKDIR /app
COPY ./@graphql .

RUN yarn install
RUN yarn run build

EXPOSE 80
ENV PORT=80
CMD ["yarn", "start"]

# CMD ["tail", "-f", "/dev/null"]
