services:
    mongo:
        container_name: mongo
        image: mongo:5.0
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_DATABASE: ${MONGO_DATABASE}
        ports:
            - ${MONGO_PORT}:27017
        volumes:
            - mongo:/data/db
        networks:
            - private

    mysql:
        container_name: mysql
        image: mariadb:10.5
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - private

    wordpress:
        container_name: wordpress
        image: wordpress:6.8.3-php8.3
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_NAME: ${MYSQL_DB}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_PORT: ${MYSQL_PORT}
            WORDPRESS_DEBUG: 1
            TZ: America/Toronto
            ACCESS_SECRET: ${ACCESS_SECRET}
            GQL_ENDPOINT: ${GQL_ENDPOINT}
            VERSION: ${VERSION}
            ENV: ${ENV}
        ports:
            - ${WP_PORT}:80
        volumes:
            - ./@wordpress/wordpress/wp-config.php:/var/www/html/wp-config.php
            # Logger Recommendation https://lnav.org/
            - ./@wordpress/debug.log:/var/www/html/wp-content/debug.log
            - ./@wordpress/plugins/resume-item:/var/www/html/wp-content/plugins/resume-item
            - ./@wordpress//theme:/var/www/html/wp-content/themes/sujin
            - ./@next/public/uploads:/var/www/html/wp-content/uploads
        depends_on:
            - mysql
        networks:
            - public
            - private

volumes:
    mongo:
    mysql:

# Private is not real private. This is just dev setting.
# Networking
#   Private: @graphql, DB
#   GQL:     @auth, @next, @wordpress, @graphql
#   mySQL:   @wordpress, mySQL
#
#   Public:  @auth, @next, @wordpress
networks:
    public:
        driver: bridge
    private:
        driver: bridge
