services:
    sujin_graphql:
        container_name: sujin_graphql
        image: sujin2f/graphql:12.0.0
        restart: always
        ports:
            - 80:80
        environment:
            SERVER_PORT:
            MONGO: sujin_mongo
            MYSQL: sujin_mysql
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DB:
            MONGO_DATABASE:
            MONGO_USER:
            MONGO_PASSWORD:
            CORS_ORIGINS: '[]'
            ACCESS_SECRET:
            REFRESH_SECRET:
            INTER_COM_SECRET:
            EMAIL_SECRET:
            CRYPTO_KEY:
        networks:
            - sujin_public
            - sujin_database
            - sujin_graphql
networks:
    sujin_public:
        external: true
        internal: false
    sujin_database:
        external: true
        internal: true
    sujin_graphql:
        external: true
        internal: true
