services:
    sujin_mongo_prod:
        container_name: sujin_mongo_prod
        image: mongo:5.0
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_DATABASE: ${MONGO_DATABASE}
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db

    # sujin_mongo_prod2:
    #     container_name: sujin_mongo_prod2
    #     image: mongo:5.0
    #     restart: always
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
    #         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    #         MONGO_USER: ${MONGO_USER}
    #         MONGO_PASSWORD: ${MONGO_PASSWORD}
    #         MONGO_DATABASE: ${MONGO_DATABASE}
    #     depends_on:
    #         - sujin_mongo_prod
    #     ports:
    #         - 37017:27017

    sujin_mysql_prod:
        container_name: sujin_mysql_prod
        image: mariadb:10.5
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306

    sujin_graphql_prod:
        container_name: sujin-graphql-prod-0.0.2-beta
        image: sujin2f/graphql:0.0.2-beta
        restart: always
        ports:
            - 8000:3000
        environment:
            MONGO: sujin_mongo_prod
            MYSQL: host.docker.internal
        depends_on:
            - sujin_mongo_prod
            - sujin_mysql_prod

volumes:
    mongo:
