services:
    sujin-mongo-prod:
        container_name: sujin-mongo-prod
        image: mongo:5.0
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_DATABASE: ${MONGO_DATABASE}
        ports:
            - ${MONGO_PORT}:27017
        volumes:
            - mongo:/data/db
        networks:
            - internal_access

    sujin-mysql-prod:
        container_name: sujin-mysql-prod
        image: mariadb:10.5
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - internal_access

    sujin-graphql-prod:
        container_name: sujin-graphql-prod-${VERSION}
        image: sujin2f/graphql:${VERSION}
        restart: always
        ports:
            - 80:80
        environment:
            MONGO: host.docker.internal
            MYSQL: mysql
        depends_on:
            - sujin-mongo-prod
            - sujin-mysql-prod
        networks:
            - sujin_graphql_bridge
            - internal_access

volumes:
    mongo:
networks:
    internal_access:
        internal: true
    sujin_graphql_bridge:
        driver: bridge
