services:
    sujin_graphql:
        container_name: sujin_graphql
        image: sujin2f/graphql:${VERSION}
        restart: always
        ports:
            - ${SERVER_PORT}:3000
        environment:
            MONGO: sujin_mongo
            MYSQL: sujin_mysql
        networks:
            - sujin_database
            - sujin_graphql

networks:
    sujin_database:
        external: true
        internal: true
    sujin_graphql:
        external: true
        internal: true
