services:
    sujin_next:
        container_name: sujin_next
        image: sujin2f/next:12.0.0
        restart: always
        environment:
            GQL_ENDPOINT:
            INTER_COM_SECRET:
            CRYPTO_KEY:
            REDIS_SERVER:
        ports:
            - 80:80
        networks:
            - sujin_public

networks:
    sujin_public:
        external: true
        internal: false
