services:
    sujin_next:
        container_name: sujin_next
        image: sujin2f/next:12.0.0
        restart: always
        environment:
            NEXT_PUBLIC_TITLE: ${NEXT_PUBLIC_TITLE}
            NEXT_PUBLIC_EXCERPT: ${NEXT_PUBLIC_EXCERPT}
            NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
            NEXT_PUBLIC_GOOGLE_AD_CLIENT: ${NEXT_PUBLIC_GOOGLE_AD_CLIENT}
            NEXT_PUBLIC_FOOTER_GOOGLE_AD_SLOT: ${NEXT_PUBLIC_FOOTER_GOOGLE_AD_SLOT}
            NEXT_PUBLIC_SIDEBAR_GOOGLE_AD_SLOT: ${NEXT_PUBLIC_SIDEBAR_GOOGLE_AD_SLOT}
            NEXT_PUBLIC_AUTH_ENDPOINT: ${NEXT_PUBLIC_AUTH_ENDPOINT}
            NEXT_PUBLIC_GQL_ENDPOINT: ${NEXT_PUBLIC_GQL_ENDPOINT}
            GQL_ENDPOINT_INTERNAL:
            INTER_COM_SECRET:
            CRYPTO_KEY:
        ports:
            - 80:80
        networks:
            - sujin_public

networks:
    sujin_public:
        external: true
        internal: false
