services:
    sujin_next:
        container_name: sujin_next
        image: sujin2f/next:12.0.0
        restart: always
        environment:
            SITE_NAME:
            SITE_DESCRIPTION:
            BASE_URL:
            GOOGLE_AD_CLIENT:
            GOOGLE_AD_SLOT_FOOTER:
            GOOGLE_AD_SLOT_SIDEBAR:
            GQL_ENDPOINT:
            AUTH_ENDPOINT:
            INTER_COM_SECRET:
            CRYPTO_KEY:
            REDIS_SERVER:
        ports:
            - 80:80
        networks:
            - sujin_public
            - sujin_redis
            - sujin_graphql

networks:
    sujin_public:
        external: true
        internal: false
    sujin_graphql:
        external: true
        internal: true
    sujin_graphql:
        external: true
        internal: true
