/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Flickr {
  /**
   * The title of the photo.
   */
  title: string;
  /**
   * Flickr URL for the image
   */
  link: string;
  /**
   * Image URLs
   */
  media: {
    origin: string;
    s: string;
    t: string;
    b: string;
    m: string;
  };
}
