/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SimplePost {
  /**
   * Unique ID
   */
  id: number;
  /**
   * Post slug
   */
  slug: string;
  /**
   * Date
   */
  date: string;
  /**
   * Link URL
   */
  link: string;
  /**
   * Title
   */
  title: string;
  /**
   * Meta data
   */
  meta?: {
    background?: Image;
    icon?: Image;
    list?: Image;
    title?: Image;
    thumbnail?: Image;
    backgroundColor?: string;
    useBackgroundColor?: boolean;
  };
  thumbnail?: Image;
}
export interface Image {
  /**
   * Large size image
   */
  large?: string;
  /**
   * Medium size image
   */
  medium?: string;
  /**
   * Small size image
   */
  small?: string;
  /**
   * Tiny size image
   */
  tiny?: string;
}
