type Query {
    tagCloud: [TagCloud]
    recent: [Post]
    prevNext(slug: String!): [Post]
    related(slug: String!): [Post]
    post2(slug: String!, isAdmin: Boolean): Post
    postByCategory(slug: String!, page: Int!, isAdmin: Boolean): [Post]
    search(keyword: String!, page: Int!, isAdmin: Boolean): [Post]
    page(slug: String!): Post

    background: [ImageBlock]
    post(
        postType: POST_TYPE!
        slug: String
        category: String
        page: Int
    ): [Post]
    postAdmin(
        postType: POST_TYPE!
        slug: String
        category: String
        page: Int
    ): [Post]
    archive(slug: String, archiveType: ARCHIVE_TYPE!, page: Int): [Archive]
    numPages(
        context: NUM_PAGES_CONTEXT!
        category: String
        type: ARCHIVE_TYPE
    ): Int
}

type Mutation {
    updatePost(slug: String!): [Boolean]
    updatePage(slug: String!): [Boolean]
    removePage(slug: String!): [Boolean]

    updateBackground: [Boolean]
    updatePosts(category: String!, page: Int!): [Boolean]
    updateSingle(postType: POST_TYPE!, slug: String!): [Boolean]
    removeSingle(postType: POST_TYPE!, slug: String!): [Boolean]
    updateHits(slug: String!): [Boolean]
    updateArchive(slug: String!, archiveType: ARCHIVE_TYPE!): [Boolean]
    removeArchive(slug: String!, archiveType: ARCHIVE_TYPE!): [Boolean]
}

type TagCloud {
    id: Int
    title: String
    slug: String
    total: Int
    hits: Int
}

type Image {
    url: String
    width: Int
    height: Int
    mimeType: String
}

type ImageSize {
    medium: Image
    mediumLarge: Image
    large: Image
    thumbnail: Image
    postThumbnail: Image
    relatedPost: Image
    recentPost: Image
}

type ImageBlock {
    _id: String
    url: String
    mimeType: String
    width: Int
    height: Int
    sizes: ImageSize
}

type Images {
    list: ImageBlock
    icon: ImageBlock
    title: ImageBlock
    background: ImageBlock
    thumbnail: ImageBlock
}

type PostMeta {
    useBackgroundColor: Boolean
    backgroundColor: String
}

type Post {
    _id: String
    id: Int
    slug: String
    title: String
    excerpt: String
    content: String
    date: Int
    link: String
    images: Images
    meta: PostMeta
    archives: [Archive]
    status: String
}

type Archive {
    _id: String
    title: String
    slug: String
    type: ARCHIVE_TYPE
    total: Int
    hits: Int
    excerpt: String
    image: ImageBlock
}

enum NUM_PAGES_CONTEXT {
    archive_list
    posts_by_category
    page_list
}

enum POST_TYPE {
    post
    page
}

enum ARCHIVE_TYPE {
    category
    tag
}
