type Query {
    # page
    page(slug: String!): Page
    pages(page: Int!): [Page]

    # post
    post(slug: String!, isAdmin: Boolean): Post # TODO rename
    posts(categorySlug: String, page: Int!, isAdmin: Boolean): PostList # category posts or all posts
    search(keyword: String!, page: Int!, isAdmin: Boolean): PostList

    # post metadata
    recent: [Post]
    prevNext(slug: String!): [Post]
    related(slug: String!): [Post]

    # backgrounds
    background: [ImageBlock]

    # archives
    tagCloud: [TagCloud]
    category(slug: String): Archive
    categories(page: Int): [Archive]
    tag(slug: String): Archive
    tags(page: Int): [Archive]
}

type Mutation {
    # page
    refreshPage(slug: String!): [Boolean]
    removePage(slug: String!): [Boolean]

    # post
    refreshPost(slug: String!): [Boolean]
    refreshPosts(categorySlug: String, page: Int!): [Boolean] # category posts or all posts
    # background
    refreshBackground: [Boolean]

    # archive
    refreshHits(slug: String!): [Boolean]
    refreshCategory(slug: String!): [Boolean]
    removeCategory(slug: String!): [Boolean]
}

type TagCloud {
    id: Int
    title: String
    slug: String
    total: Int
    hits: Int
}

# TODO fragment https://graphql.com/learn/interfaces-and-unions/#fragments
type Image {
    url: String
    width: Int
    height: Int
    mimeType: String
}

type ImageSize {
    medium: Image
    mediumLarge: Image
    large: Image
    thumbnail: Image
    postThumbnail: Image
    relatedPost: Image
    recentPost: Image
}

type ImageBlock {
    _id: String
    url: String
    mimeType: String
    width: Int
    height: Int
    sizes: ImageSize
}

type Images {
    list: ImageBlock
    icon: ImageBlock
    title: ImageBlock
    background: ImageBlock
    thumbnail: ImageBlock
}

type PostMeta {
    useBackgroundColor: Boolean
    backgroundColor: String
}

# TODO Simple type
interface Page {
    _id: String
    id: Int
    slug: String
    title: String
    excerpt: String
    content: String
    date: Int
    link: String
    images: Images
    meta: PostMeta
    status: String
}

type Page implements Page

type Post implements Page {
    archives: [Archive]
}

type PostList {
    items: [Post]
    numPages: Int
}

type Archive {
    _id: String
    title: String
    slug: String
    type: ARCHIVE_TYPE
    total: Int
    hits: Int
    excerpt: String
    image: ImageBlock
}
