// history
export const SET_HISTORY = 'sujin/v2/global/SET_HISTORY';
export type SET_HISTORY = typeof SET_HISTORY;
export const SET_MATCHED = 'sujin/v2/global/SET_MATCHED';
export type SET_MATCHED = typeof SET_MATCHED;
export const SET_LOCATION = 'sujin/v2/global/SET_LOCATION';
export type SET_LOCATION = typeof SET_LOCATION;

// global
export const SET_MOBILE_MENU = 'sujin/v2/global/SET_MOBILE_MENU';
export type SET_MOBILE_MENU = typeof SET_MOBILE_MENU;
export const SET_TITLE = 'sujin/v2/global/SET_TITLE';
export type SET_TITLE = typeof SET_TITLE;

export const REQUEST_MENU_INIT = 'sujin/v2/global/REQUEST_MENU_INIT';
export type REQUEST_MENU_INIT = typeof REQUEST_MENU_INIT;
export const REQUEST_MENU_SUCCESS = 'sujin/v2/global/REQUEST_MENU_SUCCESS';
export type REQUEST_MENU_SUCCESS = typeof REQUEST_MENU_SUCCESS;
export const REQUEST_MENU_FAIL = 'sujin/v2/global/REQUEST_MENU_FAIL';
export type REQUEST_MENU_FAIL = typeof REQUEST_MENU_FAIL;

// front-page
export const REQUEST_MAIN_BACKGROUND_INIT = 'sujin/global/REQUEST_MAIN_BACKGROUND_INIT';
export type REQUEST_MAIN_BACKGROUND_INIT = typeof REQUEST_MAIN_BACKGROUND_INIT;
export const REQUEST_MAIN_BACKGROUND_SUCCESS = 'sujin/global/REQUEST_MAIN_BACKGROUND_SUCCESS';
export type REQUEST_MAIN_BACKGROUND_SUCCESS = typeof REQUEST_MAIN_BACKGROUND_SUCCESS;
export const REQUEST_MAIN_BACKGROUND_FAIL = 'sujin/global/REQUEST_MAIN_BACKGROUND_FAIL';
export type REQUEST_MAIN_BACKGROUND_FAIL = typeof REQUEST_MAIN_BACKGROUND_FAIL;

// flickr
export const REQUEST_FLICKR_INIT = 'sujin/global/REQUEST_FLICKR_INIT';
export type REQUEST_FLICKR_INIT = typeof REQUEST_FLICKR_INIT;
export const REQUEST_FLICKR_SUCCESS = 'sujin/global/REQUEST_FLICKR_SUCCESS';
export type REQUEST_FLICKR_SUCCESS = typeof REQUEST_FLICKR_SUCCESS;
export const REQUEST_FLICKR_FAIL = 'sujin/global/REQUEST_FLICKR_FAIL';
export type REQUEST_FLICKR_FAIL = typeof REQUEST_FLICKR_FAIL;

// post
export const REQUEST_POST_INIT = 'sujin/post/REQUEST_POST_INIT';
export type REQUEST_POST_INIT = typeof REQUEST_POST_INIT;
export const REQUEST_POST_SUCCESS = 'sujin/post/REQUEST_POST_SUCCESS';
export type REQUEST_POST_SUCCESS = typeof REQUEST_POST_SUCCESS;
export const REQUEST_POST_FAIL = 'sujin/post/REQUEST_POST_FAIL';
export type REQUEST_POST_FAIL = typeof REQUEST_POST_FAIL;

export const REQUEST_RECENT_POSTS_INIT = 'sujin/post/REQUEST_RECENT_POSTS_INIT';
export type REQUEST_RECENT_POSTS_INIT = typeof REQUEST_RECENT_POSTS_INIT;
export const REQUEST_RECENT_POSTS_SUCCESS = 'sujin/post/REQUEST_RECENT_POSTS_SUCCESS';
export type REQUEST_RECENT_POSTS_SUCCESS = typeof REQUEST_RECENT_POSTS_SUCCESS;
export const REQUEST_RECENT_POSTS_FAIL = 'sujin/post/REQUEST_RECENT_POSTS_FAIL';
export type REQUEST_RECENT_POSTS_FAIL = typeof REQUEST_RECENT_POSTS_FAIL;

// page
export const REQUEST_PAGE_INIT = 'sujin/page/REQUEST_PAGE_INIT';
export type REQUEST_PAGE_INIT = typeof REQUEST_PAGE_INIT;
export const REQUEST_PAGE_SUCCESS = 'sujin/page/REQUEST_PAGE_SUCCESS';
export type REQUEST_PAGE_SUCCESS = typeof REQUEST_PAGE_SUCCESS;
export const REQUEST_PAGE_FAIL = 'sujin/page/REQUEST_PAGE_FAIL';
export type REQUEST_PAGE_FAIL = typeof REQUEST_PAGE_FAIL;

// archive
export const REQUEST_ARCHIVE_INIT = 'sujin/archive/REQUEST_ARCHIVE_INIT';
export type REQUEST_ARCHIVE_INIT = typeof REQUEST_ARCHIVE_INIT;
export const REQUEST_ARCHIVE_SUCCESS = 'sujin/archive/REQUEST_ARCHIVE_SUCCESS';
export type REQUEST_ARCHIVE_SUCCESS = typeof REQUEST_ARCHIVE_SUCCESS;
export const REQUEST_ARCHIVE_FAIL = 'sujin/archive/REQUEST_ARCHIVE_FAIL';
export type REQUEST_ARCHIVE_FAIL = typeof REQUEST_ARCHIVE_FAIL;
