type Query {
    post(slug: String!): Post
    posts(type: ARCHIVE_TYPE!, slug: String!, page: Int!): PostList
    postsAdmin(slug: String!, page: Int!): [Post]
    postsAllAdmin(page: Int!): [Post]
    search(keyword: String!, page: Int!): PostList
    # post metadata
    recent: [Post]
    prevNext(slug: String!): [Post]
    related(slug: String!): [Post]
}

type Post implements I_Page {
    _id: String
    id: Int
    slug: String
    title: String
    excerpt: String
    content: String
    date: Int
    link: String
    images: Images
    meta: PostMeta
    status: String
    archives: [Archive]
}

type PostList {
    items: [Post]
    numPages: Int
}
