query Category($slug: String!) {
    category(slug: $slug) {
        _id
        title
        slug
        excerpt
        image {
            url
            width
            height
            sizes {
                medium {
                    url
                    mimeType
                    width
                    height
                }
                mediumLarge {
                    url
                    mimeType
                    width
                    height
                }
                large {
                    url
                    mimeType
                    width
                    height
                }
            }
        }
    }
}
