services:
    sujin_auth:
        container_name: sujin_auth
        image: ${IMAGE}
        restart: always
        environment:
            CORS_ORIGINS: ${CORS_ORIGINS}
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        networks:
            - sujin_public

networks:
    sujin_public:
        external: true
        internal: false
