query {
    background {
        _id
        mimeType
        width
        height
        url
        sizes {
            medium {
                url
            }
            thumbnail {
                url
            }
            mediumLarge {
                url
            }
            postThumbnail {
                url
            }
            relatedPost {
                url
            }
            recentPost {
                url
            }
            large {
                url
            }
        }
    }
}
