query SingleMeta($type: POST_TYPE!, $slug: String) {
    post(postType: $type, slug: $slug) {
        title
        id
        excerpt
        images {
            list {
                sizes {
                    mediumLarge {
                        width
                        height
                        url
                        mimeType
                    }
                }
            }
            thumbnail {
                sizes {
                    mediumLarge {
                        width
                        height
                        url
                        mimeType
                    }
                }
            }
        }
        archives {
            title
        }
    }
}
