/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Background {
    /**
     * Desktop size image
     */
    desktop: string
    /**
     * Mobile size image
     */
    mobile: string
    /**
     * Title of the image
     */
    title: string
}
