version: '2'
services:
  db:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - local_default
  proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: >
      bash -c "touch /etc/nginx/conf.d/max_size.conf
      && echo \"client_max_body_size 100M;\" > /etc/nginx/conf.d/max_size.conf
      && forego start -r"
    ports:
      - 80:80
    restart: always
    networks:
      - local_default
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - local_default
    environment:
      VIRTUAL_HOST: mailhog.test
  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${DOCKER_DATA_PATH}/portainer:/data portainer/portainer"
    ports:
      - 9000:9000
    networks:
      - local_default
    environment:
      VIRTUAL_HOST: portainer.test
volumes:
  mysql:
networks:
  local_default:
    external: true
