services:
    # docker-compose -f docker-compose.dev.yml up -d  --remove-orphans
    sujin_wordpress_dev:
        container_name: sujin_wordpress_dev
        image: wordpress:6.8.3-php8.1
        restart: always
        environment:
            WORDPRESS_DB_HOST: sujin_mysql_dev
            WORDPRESS_DB_NAME: ${MYSQL_DB}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_PORT: ${MYSQL_PORT}
            WORDPRESS_DEBUG: 1
            TZ: America/Toronto
        ports:
            - ${WORDPRESS_PORT}:80
        volumes:
            - ./plugins/resume-item:/var/www/html/wp-content/plugins/resume-item
        # - ./theme:/var/www/html/wp-content/themes/sujin
        # - ../@next/public/uploads:/var/www/html/wp-content/uploads

        depends_on:
            - sujin_mysql_dev
        networks:
            - custom_bridge
            - mysql_network

    sujin_mysql_dev:
        container_name: sujin_mysql_dev
        image: mariadb:10.5
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - mysql_network

volumes:
    mysql:

networks:
    custom_bridge:
        external: true
    mysql_network:
        external: true
