name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: 7.3
        extension-csv: intl

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install

    - name: npm install and test
      run: |
        npm ci
        npm run arson
      env:
        CI: true
        MYSQL_ROOT_PASSWORD: password
