# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NEXT.js CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        container:
            image: node:22

        steps:
            - name: Install MongoSH
              run: |
                  apt-get install gnupg
                  wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | tee /etc/apt/trusted.gpg.d/server-7.0.asc
                  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
                  apt-get update
                  apt-get install -y mongodb-mongosh
                  mongosh --version

            - name: Initialize MongoDB
              run: |
                  mongosh --host localhost:27017 -u admin -p admin --authenticationDatabase admin <<EOF
                      db.createUser({ user: 'test', pwd: 'test', roles: [{ role: 'readWrite', db: 'test' }, { role: 'dbAdmin', db: 'test' }] });
                  EOF

            - name: Git checkout
              uses: actions/checkout@v3

            - name: Yarn Install
              uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: install # will run `yarn install` command

            - name: Lint
              uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: lint # will run `yarn lint` command

            - name: Test
              uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: test # will run `yarn test` command
              env:
                  MONGO: mongodb
                  MONGO_DATABASE: test
                  MONGO_USER: test
                  MONGO_PASSWORD: test
