# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NEXT.js CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        container:
            image: node:22

        services:
            mongodb:
                image: mongo
                ports:
                    - 27017:27017

        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Yarn Install
              uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: install # will run `yarn install` command

            - name: Lint
              uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: lint # will run `yarn lint` command

            - name: Build
              uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: build # will run `yarn build` command

            - name: Test
              uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: test # will run `yarn test` command
              env:
                  MONGO: mongodb
                  MONGO_DATABASE: test
