# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: sujinc.com CI

on: [push]

jobs:
    push:
        runs-on: ubuntu-latest

        container:
            image: node:24

        steps:
            - name: Git checkout
              uses: actions/checkout@v5

            - name: Yarn/Composer Install
              uses: borales/actions-yarn@v3.0.0
              uses: php-actions/composer@v6
              with:
                  cmd: install-modules # install dependencies

            - name: Lint
              uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: lint

            - name: Test
              uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: test

            - name: Build # common & library modules validation
              uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: build
